## Лабораторная работа №1 | Вариант 4

Выполнил: 

### 1. Numpy


In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
import os

warnings.filterwarnings('ignore')

plt.style.use('seaborn-v0_8')
sns.set_palette("husl")
pd.set_option('display.max_columns', None)


1. Найти индексы не нулевых элементов массива [1,2,0,0,4,0]

In [10]:
# Поиск индексов ненулевых элементов
vector = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.where(vector != 0)[0]
print(f"1. Индексы не нулевых элементов: {non_zero_indices}")

1. Индексы не нулевых элементов: [0 1 4]


2. Создайте единичную матрицу размером 3х3

In [13]:
identity_matrix = np.identity(3)
print("2. Единичная матрица 3x3:")
print(identity_matrix)

2. Единичная матрица 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3. Создайте матрицу-шахматную доску 8х8 используя функцию `tile`

In [6]:
base_pattern = np.array([[0, 1], [1, 0]])
chess_board = np.tile(base_pattern, (4, 4))
print("3. Шахматная доска 8x8:")
print(chess_board)

3. Шахматная доска 8x8:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


4. Дан 1D массив, удалите все элементы которые входят в диапазон `[3, 8]` inplace

In [8]:
arr = np.array([0, 4, 4, 2, 1, 4, 8, 7, 10, 15])
print("Исходный массив:", arr)
mask = (arr < 3) | (arr > 8)
arr = arr[mask]
print("После удаления элементов [3,8]:", arr)

Исходный массив: [ 0  4  4  2  1  4  8  7 10 15]
После удаления элементов [3,8]: [ 0  2  1 10 15]


5. Создайте случайный вектор размером 10 элементов и замените максимальный элемент на 0

In [22]:
random_vector = np.random.random(10)
print("Исходный вектор:", random_vector)
max_value_index  = np.argmax(random_vector)
random_vector[max_value_index] = 0
print("После замены максимума на 0:", random_vector)

Исходный вектор: [0.86310343 0.62329813 0.33089802 0.06355835 0.31098232 0.32518332
 0.72960618 0.63755747 0.88721274 0.47221493]
После замены максимума на 0: [0.86310343 0.62329813 0.33089802 0.06355835 0.31098232 0.32518332
 0.72960618 0.63755747 0.         0.47221493]


6. Как распечатать все значения в массиве?

In [23]:
sample_array = np.arange(20).reshape(4, 5)

print("Метод 1 - прямое отображение:")
np.set_printoptions(threshold=np.inf)
print(sample_array)

print("\nМетод 2 - итерация по элементам:")
print("Элементы:", end=" ")
for element in sample_array.ravel():
    print(element, end=" ")
print()

print("\nМетод 3 - преобразование в одномерный массив:")
print(sample_array.flatten())

Метод 1 - прямое отображение:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Метод 2 - итерация по элементам:
Элементы: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

Метод 3 - преобразование в одномерный массив:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


7. Рассмотрим случайный вектор с формой 100х2, представляющей координаты, и найдем расстояния от точки к точке

In [27]:
coordinates = np.random.rand(100, 2)
coordinate_differences = np.diff(coordinates, axis=0)
point_distances = np.sqrt(np.sum(coordinate_differences**2, axis=1))

print(f"Количество точек: {coordinates.shape[0]}")
print(f"Количество расстояний между точками: {len(point_distances)}")
print(f"Все расстояния между последовательными точками:")
print(point_distances)
print(f"\nСтатистика расстояний:")
print(f"Минимальное расстояние: {point_distances.min():.6f}")
print(f"Максимальное расстояние: {point_distances.max():.6f}")
print(f"Среднее расстояние: {point_distances.mean():.6f}")
print(f"Стандартное отклонение: {point_distances.std():.6f}")

Количество точек: 100
Количество расстояний между точками: 99
Все расстояния между последовательными точками:
[0.25947917 0.5383771  0.1762599  0.16747384 0.57216096 0.21267693
 0.89811606 0.31543771 0.14513571 0.51282653 0.34220086 0.53203227
 0.48305719 0.74412477 0.9822242  1.03614014 0.5178635  0.43718726
 0.63463293 0.65199014 0.5795774  0.46826516 0.06929961 0.4421272
 0.07914964 0.34888921 0.65048212 0.38698557 0.52877299 0.85030986
 0.79174677 0.67034356 0.54686648 0.37426159 0.88221144 0.44293429
 0.27659011 0.79088958 0.42402588 0.2328173  0.44948121 0.71402582
 0.80637551 0.49744152 0.10182197 0.48406228 0.56711633 0.64737576
 0.55975209 0.47500229 0.35343854 0.55306106 0.96418572 0.42796673
 0.77003313 0.47267729 0.19995406 0.54415909 0.94534638 0.9009664
 0.86407284 0.8467469  0.30329875 0.54029454 0.81787207 0.61250677
 0.56011695 0.60391815 0.40507172 0.51289647 0.2884765  0.43201718
 0.42029733 0.4296023  0.56835493 0.34019341 0.54723508 0.5856823
 0.5787518  0.46175936

8. Как конвертировать массив float(32 bit) к массиву целых чисел (integer 32 bit) in place?

In [36]:
def convert_float_to_int_preserving(float_array):
    max_decimals = 0
    for value in float_array:
        if value % 1 != 0:
            decimal_str = f"{value:.6f}".split('.')[1].rstrip('0')
            max_decimals = max(max_decimals, len(decimal_str))
    
    scale = 10 ** min(max_decimals, 100)  
    
    scaled_int_array = (float_array * scale).astype(np.int32)
    
    return scaled_int_array, scale

original_data = np.array([1.7, 2.3, 3.9, 4.1, 5.8], dtype=np.float32)

print("Исходный массив:", original_data)
print("Тип:", original_data.dtype)

simple_int = original_data.astype(np.int32)
print("Простое преобразование:", simple_int)
print("Потеря данных:", original_data - simple_int)

scaled_int, scale_factor = convert_float_to_int_preserving(original_data)
print("Умное преобразование:", scaled_int)

restored_data = scaled_int.astype(np.float32) / scale_factor
print("Восстановленные данные:", restored_data)
print("Точное восстановление:", np.allclose(original_data, restored_data))

Исходный массив: [1.7 2.3 3.9 4.1 5.8]
Тип: float32
Простое преобразование: [1 2 3 4 5]
Потеря данных: [0.70000005 0.29999995 0.9000001  0.0999999  0.80000019]
Умное преобразование: [17 23 39 41 58]
Восстановленные данные: [1.7 2.3 3.9 4.1 5.8]
Точное восстановление: True


9. Как прочитать заданный файл?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [41]:
with open('data.txt', 'w') as f:
    f.write("1, 2, 3, 4, 5\n")
    f.write("6,  ,  , 7, 8\n")
    f.write(" ,  , 9,10,11\n")

if os.path.exists('data.txt'):
    print("Файл data.txt успешно создан")
    
    file_size = os.path.getsize('data.txt')
    if file_size > 0:
        print(f"Размер файла: {file_size} байт")
        
        data = np.genfromtxt('data.txt', delimiter=',', filling_values=np.nan)
        
        print("Данные из файла:")
        print(data)
        print(f"Форма массива: {data.shape}")
        print(f"Тип данных: {data.dtype}")
        
        if data.shape == (3, 5):
            print("Данные прочитаны корректно")
        else:
            print("Ошибка: неверная форма данных")
    else:
        print("Ошибка: файл пустой")
else:
    print("Ошибка: файл не создан")

Файл data.txt успешно создан
Размер файла: 45 байт
Данные из файла:
[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]
Форма массива: (3, 5)
Тип данных: float64
Данные прочитаны корректно


10. Какой эквивалент enumerate для numpy массивов?

In [47]:
sample_1d = np.array(['a', 'b', 'c', 'd', 'e'])

print("Способ 1 - перебор с индексами:")
for index, value in enumerate(sample_1d):
    print(f"Позиция {index}: значение '{value}'")

print("\nСпособ 2 - многомерное индексирование:")
sample_2d = np.array([[10, 20, 30], [40, 50, 60]])
for coords, val in np.ndenumerate(sample_2d):
    print(f"Координаты {coords}: значение {val}")

Способ 1 - перебор с индексами:
Позиция 0: значение 'a'
Позиция 1: значение 'b'
Позиция 2: значение 'c'
Позиция 3: значение 'd'
Позиция 4: значение 'e'

Способ 2 - многомерное индексирование:
Координаты (0, 0): значение 10
Координаты (0, 1): значение 20
Координаты (0, 2): значение 30
Координаты (1, 0): значение 40
Координаты (1, 1): значение 50
Координаты (1, 2): значение 60


### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом 

Файл: `russian-housing-market.csv`

```
price_doc - Цена продажи
id - Id транзакции
timestamp - Дата транзакции
full_sq - суммарная площадь в квадратных метрах, включая лоджию, валконы и отдельные нежилые помещения
life_sq - жилая площаль в квадратных метрах, исключая лоджии, балконы и прочие нежилые помещения
floor - для апартаментов, этаж помещения
max_floor - количество этажей в здании
material - материал стен
build_year - год постройки
num_room - количество жилых комнат
kitch_sq - площадь кухни
state - состояние апартаментов
product_type - покупка или инвестиция собственника-арендатора
sub_area - название района
```

In [45]:
import pandas as pd
import numpy as np


In [44]:
housing_data = pd.read_csv('russian-housing-market.csv')
print(f"Размер dataset: {housing_data.shape}")
print(f"Колонки: {list(housing_data.columns)}")

Размер dataset: (30471, 14)
Колонки: ['id', 'timestamp', 'full_sq', 'life_sq', 'floor', 'max_floor', 'material', 'build_year', 'num_room', 'kitch_sq', 'state', 'product_type', 'sub_area', 'price_doc']


1. Посчитайте количество записей в датасете с отсутствующей информацией о жилой площади жилого помещения

In [46]:
missing_living_sq = housing_data['life_sq'].isna().sum()
total_records = len(housing_data)

print(f"Всего записей в dataset: {total_records}")
print(f"Записей с пропуском жилой площади: {missing_living_sq}")
print(f"Процент пропусков: {missing_living_sq/total_records*100:.2f}%")

Всего записей в dataset: 30471
Записей с пропуском жилой площади: 6383
Процент пропусков: 20.95%


2. Предложите способ заменить отсутствующие значения из пункта 1 и реализуйте его. Способ нужно аргументировать(сказать почему это достаточно хорошее приближение)

3. Какие значения имеет 25, 50 и 75 перцентили полной площади помещения

4. Посчитайте среднюю стоимость продажи помещений с общей площадью от 50 до 70 квадратных метров

5. Какая максимальная этажность здания представлена в датасете

6. Выявите район с самым дорогим жильем

7. Посчитайте среднюю стоимость за квадратный метр жилья в Митино(Mitino)

8. Посчитайте среднюю площадь комнаты в Бибирево

9. Проанализируйте есть ли разница в цене между квартирами на 1 и 9 этажах

10. Найдите минимальную стоимость квартиры с жилой площадью не менее 60 квадратных метров, не менее чем 3мя комнатами и не ниже чем на 5 этаже

### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

1. Как менялась средняя цена квартиры в Нагатинском Затоне(Nagatinski Zaton) с течением времени

2. Постройте гистограмму распределения цен на квартиры с общей площадью более 50 кв.метров

3. Визуализируйте количество проданных квартир в разных районах

4. Постройте box plot отображающий распределение полных площадей квартир в Басманном районе

5. Визуализируйте зависимость средней стоимости квартир в зависимости от этажа

6. Покажите как меняется средняя площадь квартир в зависимости от района

7. Постройте график изменения медианной цены на квартиру менее 50 кв. метров за период с 2011 до 2014 года*

\* Задание на доп. балл